name: JulioEPD
title: Blog do Julio
description: Site construido usando template Jekyll Netflix
tags:
  - blog
  - jekyll
  - theme
  - netlify
email: youremail@xyz.com
disqus_username: julioepd
show_hero: true
